### ISSUE TITLE
Handle spread of non-object

### ISSUE THREAD

**Issue by AlbertLucianto** [felixputera/ts-transform-object-spread#1]
In [proposal-object-rest-spread](https://tc39.es/proposal-object-rest-spread/#AbstractOperations-CopyDataProperties), it is stated that:

> 3. If source is `undefined` or `null`, let keys be a new empty `List`.

Practically, you can try on Chrome console to see the output of non-object spread. As an example:

![Screenshot 2019-12-01 at 12 27 36 PM](https://user-images.githubusercontent.com/23165866/69909431-fbe2fa00-1435-11ea-87c9-61af26508ff0.png)

Currently, if you do this (spreading non object), typescript will raise

> Spread types may only be created from object types.ts(2698)

But actually it's allowed and here's an [issue related to this](https://github.com/microsoft/TypeScript/issues/10727).

**Comment by felixputera** [comment]
If I'm understanding correctly, you're expecting this transform to allow spreading non-object as per the ES proposal.

I'd say that this is not the objective of this transform (and sorry for choosing a ambiguous name), which is to re-write spreaded objects as property assignments. I had updated the README (https://github.com/felixputera/ts-transform-object-spread#motivation) with more details so I hope that it clarifies my intention!

Thanks for opening an issue anyway!
